### ISSUE TITLE
Fix websocket open error

### ISSUE THREAD

**Issue by thanhnp95** [chaineco/bisonexplorer#132]
At the footer of subpages. When redirected from homepage, due to the influence of turbolink. socket open status is not opened properly
![Image](https://github.com/user-attachments/assets/efbd305e-9dbc-40f2-a255-9a07cb0ff1a3)

**Comment by thanhnp2k** [comment]
Fixed:
https://github.com/chaineco/blockcare/commit/d2a50fb6bbc363d3ad4aaab33c527843d8694af9
