### ISSUE TITLE
Test all

### ISSUE THREAD

**Issue by trando95** [chaineco/bisonexplorer#163]

**Comment by thanhnp2k** [comment]
Bug summary:
- Volume on Market chart is incorrect or in wrong units
![Image](https://github.com/user-attachments/assets/b7cb61cf-5080-48be-a227-0acb06d3d09b)
![Image](https://github.com/user-attachments/assets/9c9a69bc-4105-4be7-ac13-f4af6dbd5bc9)

**Comment by thanhnp2k** [comment]
The background color of the Chain chart is not appropriate. Control all effects of common card background color
![Image](https://github.com/user-attachments/assets/17532c8f-3b02-4a62-9a31-ee5250bff05b)

**Comment by thanhnp2k** [comment]
**Issue 4: ** Columns on blocks page have misaligned data on normal and mobile view
![Image](https://github.com/user-attachments/assets/72f314cd-0ec1-4139-9324-08950610d4e4)
![Image](https://github.com/user-attachments/assets/e0d36a1e-476f-49c3-9697-da928052a6c2)

**Comment by thanhnp2k** [comment]
**Issue 5: **  Visual blocks not displaying correctly on mobile view (blocks page)
Implementation: Fix color description, remove unnecessary columns on the table and display visual blocks with reasonable width
![Image](https://github.com/user-attachments/assets/05e43697-6a78-4311-abb6-db03c945bb0a)

**Comment by thanhnp2k** [comment]
**Issue 5**: Month view report is difficult to view in mobile view
https://github.com/user-attachments/assets/90cab665-ca77-4c5e-a524-711a7b8a0370

**Comment by thanhnp2k** [comment]
**Issue 6:** Use Month Average toggle is not aligned on mobile view
![Image](https://github.com/user-attachments/assets/8112baa2-8252-4b62-a6a9-1364a78ccade)

**Comment by thanhnp2k** [comment]
**Isssue 7: ** Treasury Type selector does not wrap when the screen is minimized
![Image](https://github.com/user-attachments/assets/92954d74-8692-44b0-a03e-ab1e9aaad7c5)

**Comment by thanhnp2k** [comment]
**Issue 8:** Proposals table overflows screen on mobile view (detail report)
![Image](https://github.com/user-attachments/assets/41b8525c-9f5c-49d5-8204-33e25ad05378)

**Comment by thanhnp2k** [comment]
**Issue 9: ** Bad gateway when search
![Image](https://github.com/user-attachments/assets/b6606acb-130e-48a3-8f1a-660b39c0141b)

**Comment by thanhnp2k** [comment]
Fix some UI components

**Comment by thanhnp2k** [comment]
Searchbox right aligned off table
![Image](https://github.com/user-attachments/assets/c9460e60-9b74-4f66-bd55-f1fd1e7eaa00)

**Comment by thanhnp2k** [comment]
Index error when jumping to legacy transaction page from report page
https://github.com/user-attachments/assets/54567317-64c8-445f-802b-5fb06c8357bb

**Comment by thanhnp2k** [comment]
Calculate Total Spent (%) on the Total line
![Image](https://github.com/user-attachments/assets/e6293320-250f-4552-8817-eb4c3e981175)

**Comment by thanhnp2k** [comment]
Some new elements have inconsistent colors in night mode
![Image](https://github.com/user-attachments/assets/ab0c5164-9306-4bf6-9ae3-a3f8bd641581)
![Image](https://github.com/user-attachments/assets/456df87d-f4e9-474c-9c56-0aa803b43a07)
![Image](https://github.com/user-attachments/assets/23200b38-dfde-46fa-b2bc-eaeeed73a199)
